### ISSUE TITLE
How do I use this in windows

### ISSUE THREAD

**Issue by creationix** [SublimeLinter/SublimeLinter-luacheck#2]
I finally got luacheck installed on windows (no easy feat).  With sublimelinter running in debug mode, I can see it's running luacheck against my code and outputting the proper warnings to the console, but the sublime UI seems to think there are no errors or warnings?  Has this been tested in windows and if so, how do I get it to work?

![capture](https://cloud.githubusercontent.com/assets/89353/5648023/ace435e4-9650-11e4-9951-5b1bd2d8c80b.PNG)

**Comment by skj3gg** [comment]
Thanks for this! The regex was not ready for a `C:\` style file path and wasn't matching any errors. Change has been made and should be in Package Control soon.

Watch the Last Seen value on https://packagecontrol.io/packages/SublimeLinter-luacheck and once it says version 1.0.3, it should update when you restart ST3

**Comment by creationix** [comment]
Doesn't appear to be working.  I've got it cloned locally, but I don't know
enough python regex to debug it.  I'll see if I can figure it out.

**Comment by skj3gg** [comment]
Really sorry about that, trying to make the changes from a computer that doesn't have `luacheck` so it was a well educated guess. Try replacing the linter.py regex `r'^(c:)?(?P<filename>[^:]+):(?P<line>\d+):(?P<col>\d+): (?P<message>.*)$'` with  `r'^(?P<filename>.+):(?P<line>\d+):(?P<col>\d+): (?P<message>.*)$'` and see if that doesn't resolve your issue.

**Comment by creationix** [comment]
yep, that does it!

**Comment by skj3gg** [comment]
Awesome, feel free to make a PR otherwise I'll do it

**Comment by creationix** [comment]
I'll let you do it if that's fine.

**Comment by skj3gg** [comment]
Thanks again, should go live soon.
