### ISSUE TITLE
readme incorrectly lists settings

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter-luacheck#22]
I don't think those settings are used anymore, right @kaste?

**Comment by kaste** [comment]
Removed 3 years ago! https://github.com/SublimeLinter/SublimeLinter-luacheck/commit/8d0c87b21b17f0567dc4ce642437860cdf35bc6b#diff-6c1f4f1574c85da37dc4dd59341c9a39

**Comment by braver** [comment]
🤦‍♂️
