### ISSUE TITLE
The ReadMe links to documentation that allegedly tells one how to install luacheck but does not actually do so

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [SublimeLinter/SublimeLinter-luacheck#23]
The ReadMe contains this:

> Before using this plugin, ensure that luacheck is installed on your system. To install luacheck, follow the instructions at the luacheck home page.

Yet, the linked page contains a contents list, no item of which seems relevant. Even searching that list - via a search box provided - does not seem to supply installation instructions for luacheck.

The following worsens matters. On Linux Mint and Ubuntu (and hence Debian) the repositories contain luacheck but under the name . . `lua-check`, with a hyphen. That means one can fail to find the package in the repository,

**Comment by kaste** [comment]
Fixed the link.  They currently recommend

```
luarocks install luacheck
```
