### ISSUE TITLE
.luacheckrc is not read

### ISSUE THREAD

**Issue by linuxmaniac** [SublimeLinter/SublimeLinter-luacheck#3]
if the project has a .luacheckrc file with the global configs the plugin does not recognize the configs defined there.

See http://luacheck.readthedocs.org/en/0.11.0/config.html for details of the file

**Comment by daurnimator** [comment]
this would be great :D

**Comment by doitian** [comment]
`.luacheckrc` works for me, but the problem is that per file and per path settings do not work. I guess that the linter is executed against a temporary file, which path is different.
