### ISSUE TITLE
I/O error with luacheck

### ISSUE THREAD

**Issue by vadi2** [SublimeLinter/SublimeLinter-luacheck#5]
The linter keeps failing with an I/O error:

```
SublimeLinter: luacheck: config.lua ['/usr/local/bin/luacheck', '@', 'global', '--ignore', 'channel'] 
SublimeLinter: luacheck output:
Checking /tmp/SublimeLinter3-vadi/config.lua      Syntax error
Checking global                                   I/O error
```

I've verified that luacheck works correctly in the terminal and that the linter is using the same luacheck binary, and that the files inside /tmp/SublimeLinter3-vadi/ are getting created and deleted. No results seem to be read from luacheck however.

**Comment by vadi2** [comment]
The luac linter works fine.

**Comment by braver** [comment]
Closed due to age
