### ISSUE TITLE
Specifying `include_files` in .luacheckrc stops finding linter errors

### ISSUE THREAD

**Issue by tyrondis** [SublimeLinter/SublimeLinter-luacheck#9]
Have a `.luacheckrc` and specify the following:

`include_files = { '.luacheckrc', '**/*.lua' }`

Now this plugin will not report _any_ linter errors anymore. Debug output is always:

`Total: 0 warnings / 0 errors in 1 file`

even though the file clearly has errors. Removing the `include_files` fixed it again.

**Comment by braver** [comment]
Closed due to age. If we need to dig into this, please include [debug logs](http://www.sublimelinter.com/en/stable/troubleshooting.html).
